// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`dart-json tests matches report snapshot 1`] = `
TestRunResult {
  "path": "fixtures/dart-json.json",
  "suites": Array [
    TestSuiteResult {
      "groups": Array [
        TestGroupResult {
          "name": "Test 1",
          "tests": Array [
            TestCaseResult {
              "error": undefined,
              "name": "Test 1 Passing test",
              "result": "success",
              "time": 36,
            },
          ],
        },
        TestGroupResult {
          "name": "Test 1 Test 1.1",
          "tests": Array [
            TestCaseResult {
              "error": Object {
                "line": 13,
                "message": "Expected: <2>
  Actual: <1>
",
                "path": "test/main_test.dart",
                "stackTrace": "package:test_api          expect
test\\\\main_test.dart 13:9  main.<fn>.<fn>.<fn>
",
              },
              "name": "Test 1 Test 1.1 Failing test",
              "result": "failed",
              "time": 20,
            },
            TestCaseResult {
              "error": Object {
                "line": 2,
                "message": "Exception: Some error",
                "path": "lib/main.dart",
                "stackTrace": "package:darttest/main.dart 2:3  throwError
test\\\\main_test.dart 17:9        main.<fn>.<fn>.<fn>
",
              },
              "name": "Test 1 Test 1.1 Exception in target unit",
              "result": "failed",
              "time": 6,
            },
          ],
        },
        TestGroupResult {
          "name": "Test 2",
          "tests": Array [
            TestCaseResult {
              "error": Object {
                "line": 24,
                "message": "Exception: Some error",
                "path": "test/main_test.dart",
                "stackTrace": "test\\\\main_test.dart 24:7  main.<fn>.<fn>
",
              },
              "name": "Test 2 Exception in test",
              "result": "failed",
              "time": 12,
            },
          ],
        },
      ],
      "name": "test\\\\main_test.dart",
      "totalTime": undefined,
    },
    TestSuiteResult {
      "groups": Array [
        TestGroupResult {
          "name": null,
          "tests": Array [
            TestCaseResult {
              "error": Object {
                "line": 5,
                "message": "TimeoutException after 0:00:00.000001: Test timed out after 0 seconds.",
                "path": "test/second_test.dart",
                "stackTrace": "dart:isolate  _RawReceivePortImpl._handleMessage
",
              },
              "name": "Timeout test",
              "result": "failed",
              "time": 37,
            },
            TestCaseResult {
              "error": undefined,
              "name": "Skipped test",
              "result": "skipped",
              "time": 14,
            },
          ],
        },
      ],
      "name": "test\\\\second_test.dart",
      "totalTime": undefined,
    },
  ],
  "totalTime": 3760,
}
`;
